# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d72428cbb5b80eb86f7eedaa2dbd185799890b959cbf551385da758d33a3ef73744098f54cb4cc5cd0a53d63a43e15fff86d8e0cc17e0ac862f431e2782f9fc

test:
  secret_key_base: be01c1918f642ec3d3144c863f9f4569be1a51b26ff3db25bc5e03a5dbfa07557e8a5814b8d68a6ef2a4467b6d0f6fb34bd67748247666a1856c12c3a4c1a286

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
